FROM python:3.10-slim as builder

WORKDIR /app

COPY requirements.txt requirements-dev.txt ./

RUN pip install --no-cache-dir -r requirements-dev.txt

FROM python:3.10-slim

WORKDIR /app

COPY --from=builder /usr/local/lib/python3.10/site-packages /usr/local/lib/python3.10/site-packages
COPY --from=builder /usr/local/bin /usr/local/bin

COPY ./app ./app

COPY ./build.py ./
COPY ./frontend ./frontend

RUN python3 build.py

EXPOSE 8000

# The command to run the application using the Gunicorn production server
# We use Gunicorn to manage Uvicorn workers for better performance and stability.
CMD ["gunicorn", "-w", "4", "-k", "uvicorn.workers.UvicornWorker", "app.main:app", "--bind", "0.0.0.0:8000"]